"""reversed model with payout data

Revision ID: 01e3bbb2d650
Revises: 143724205139
Create Date: 2026-09-14 19:01:17.811513

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01e3bbb2d650'
down_revision: Union[str, None] = '143724205139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'currency_code')
    op.drop_column('payouts', 'payment_service_id')
    op.drop_column('payouts', 'created_at')
    op.drop_column('payouts', 'fx_rate')
    op.drop_column('payouts', 'base_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('base_amount', sa.FLOAT(), nullable=False))
    op.add_column('payouts', sa.Column('fx_rate', sa.FLOAT(), nullable=False))
    op.add_column('payouts', sa.Column('created_at', sa.DATETIME(), nullable=False))
    op.add_column('payouts', sa.Column('payment_service_id', sa.VARCHAR(), nullable=False))
    op.add_column('payouts', sa.Column('currency_code', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
