"""updated model with payout data

Revision ID: 143724205139
Revises: 03b72ef37440
Create Date: 2026-09-14 10:00:51.918309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143724205139'
down_revision: Union[str, None] = '03b72ef37440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('payment_service_id', sa.String(), nullable=False))
    op.add_column('payouts', sa.Column('currency_code', sa.String(), nullable=False))
    op.add_column('payouts', sa.Column('fx_rate', sa.Float(), nullable=False))
    op.add_column('payouts', sa.Column('base_amount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'base_amount')
    op.drop_column('payouts', 'fx_rate')
    op.drop_column('payouts', 'currency_code')
    op.drop_column('payouts', 'payment_service_id')
    # ### end Alembic commands ###
