"""reversed model with payout data

Revision ID: 65b48d2eda7f
Revises: 01e3bbb2d650
Create Date: 2026-09-14 19:14:22.899055

"""
from datetime import datetime, timezone
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65b48d2eda7f'
down_revision: Union[str, None] = '01e3bbb2d650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'payouts',
        sa.Column('created_at', sa.DateTime(), nullable=True)
    )

    # 2. Backfill existing rows with a constant Python timestamp
    # Using a constant avoids the "non-constant default" issue
    payouts = sa.table('payouts', sa.column('created_at', sa.DateTime()))
    op.execute(
        payouts.update().values(
            created_at=datetime.now(timezone.utc)
        )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts', 'created_at')
    # ### end Alembic commands ###
