"""modified payout inbox table

Revision ID: 825b8acfd29a
Revises: d30b2201120c
Create Date: 2026-09-27 14:22:23.235941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825b8acfd29a'
down_revision: Union[str, None] = 'd30b2201120c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts_outbox', sa.Column('processed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payouts_outbox', 'processed_at')
    # ### end Alembic commands ###
