"""create payout inbox table

Revision ID: d30b2201120c
Revises: 
Create Date: 2026-09-27 12:07:08.398082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd30b2201120c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payouts_outbox',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('payout_reference_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(length=10), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=3), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payouts_outbox_created_at'), 'payouts_outbox', ['created_at'], unique=False)
    op.create_index(op.f('ix_payouts_outbox_status'), 'payouts_outbox', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payouts_outbox_status'), table_name='payouts_outbox')
    op.drop_index(op.f('ix_payouts_outbox_created_at'), table_name='payouts_outbox')
    op.drop_table('payouts_outbox')
    op.drop_table('payouts')
    # ### end Alembic commands ###
