"""create payout status table 

Revision ID: 9e4be169c063
Revises: 
Create Date: 2026-09-18 20:45:30.925941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9e4be169c063'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payouts_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('payment_service_id', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=3), nullable=True),
    sa.Column('fx_rate', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('base_amount', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payouts_status')
    # ### end Alembic commands ###
